import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const BANNER = "// GENERATED by CAR - DO NOT EDIT\n";
const STATIC_DIR = "src/codex_autorunner/static";

const entries = await readdir(STATIC_DIR, { withFileTypes: true });

for (const entry of entries) {
  if (!entry.isFile()) continue;
  if (!entry.name.endsWith(".js")) continue;

  const filePath = join(STATIC_DIR, entry.name);
  const contents = await readFile(filePath, "utf8");
  if (contents.startsWith(BANNER)) continue;

  await writeFile(filePath, `${BANNER}${contents}`, "utf8");
}
